from __future__ import annotations

from html import escape
from urllib.parse import urlencode

from .models import Estimate, Verdict

_BADGE_COLORS = {
    Verdict.COMFORTABLE: "#238636",
    Verdict.TIGHT: "#9a6700",
    Verdict.UNLIKELY: "#da3633",
    Verdict.UNKNOWN: "#6e7781",
}


def build_share_query(
    model: str, memory_gb: float, context: int, concurrency: int, kv_dtype: str
) -> str:
    """Build a stable, URL-safe query string for a reproducible web check."""
    memory_value = float(memory_gb)
    memory = int(memory_value) if memory_value.is_integer() else memory_value
    return urlencode(
        {
            "model": model,
            "memory": memory,
            "context": context,
            "concurrency": concurrency,
            "kv_dtype": kv_dtype,
        }
    )


def markdown_report(result: Estimate) -> str:
    """Render a portable report suitable for issues, model cards, and chat."""
    peak = (
        f"{result.low_gb:.2f}-{result.high_gb:.2f} GB"
        if result.low_gb is not None and result.high_gb is not None
        else "unknown"
    )
    return "\n".join(
        [
            f"# Mac AI Doctor: {result.model.model_id}",
            "",
            f"**{result.verdict.value}** ({result.confidence} confidence)",
            "",
            "| Setting | Value |",
            "| --- | ---: |",
            f"| Available memory | {result.available_gb:.1f} GB |",
            f"| Context | {result.context:,} tokens |",
            f"| Concurrency | {result.concurrency} |",
            f"| KV dtype | {result.kv_dtype} |",
            f"| Estimated peak | {peak} |",
            "",
            "> Screening estimate, not a benchmark. Model weights were not downloaded.",
            "",
            "Generated by [Mac AI Doctor](https://github.com/barvhaim/mac-ai-doctor).",
        ]
    )


def badge_svg(label: str, verdict: Verdict) -> str:
    """Return a standalone, escaped SVG badge for a computed result."""
    safe_label = escape(label[:36])
    safe_verdict = escape(verdict.value.lower())
    color = _BADGE_COLORS[verdict]
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="260" height="28" role="img" '
        f'aria-label="{safe_label}: {safe_verdict}">'
        '<rect width="260" height="28" rx="6" fill="#24292f"/>'
        f'<rect x="174" width="86" height="28" rx="6" fill="{color}"/>'
        '<path d="M174 0h6v28h-6z" fill="#24292f"/>'
        '<g fill="#fff" font-family="Verdana,Arial,sans-serif" font-size="11">'
        f'<text x="87" y="18" text-anchor="middle">{safe_label}</text>'
        f'<text x="217" y="18" text-anchor="middle">{safe_verdict}</text>'
        "</g></svg>"
    )
